Simple child Tracking
Calandiel/SongsOfGPL pull request #179
Opened 2024-02-13 15:08 UTC by squealingpiggies

The changes to code for the test simulations in #175

2024-02-14 11:26 UTC, Calandiel requested changes
The children button seems to be too small:
![image](https://github.com/Calandiel/SongsOfGPL/assets/10187653/f8528782-0f57-4eab-b804-c193595939a1)

2024-02-14 11:27 UTC, Calandiel commented
Besides that, seems fine, wdyt? @ineveraskedforthis

2024-02-14 16:02 UTC, ineveraskedforthis approved these changes
Looks fine.

2024-02-14 23:10 UTC, squealingpiggies commented
I don't know if these changes should actually be included, it was more of a proof of concept to see how it affected growth (that was asked for in the related issue discussion). It should probably be looked at a bit more in depth before merging.

2024-02-15 01:06 UTC, Calandiel commented
Child tracking and the UI for it at least ought to be included, imhp

2024-02-15 03:28 UTC, squealingpiggies commented
Ok, fair enough. I fixed the UI and made a very generic list-widget that takes any list and a table of columns from the character-list widget which is shown off with an additional tab in characters that shows their warriors. The list-widget still needs to have the bounds be anchors and stretch the columns using the closures as weighted widths instead of pixel values but it is getting to be both very versatile and easy to use.

2024-02-16 06:26 UTC, squealingpiggies commented
One last additon to ui changes. I added scaling calculations to the table widget from _engine.ui_ to weight the widths of the render closures and scale table items into the rect provided. It seems to work for both the standard _character-list_ and the generic _list-widget_ without changes to either's code.

2024-02-17 08:40 UTC, Calandiel commented
Seems fine to me, thanks!

2024-02-17 08:40 UTC, merged